Repository orange-cloudavenue/cloudavenue-sdk-go, pull requests merged in 2024-12, with the labels that each got.

#154 chore: rename UUID package to URN
  .changelog/154.txt
  pkg/clients/cloudavenue/org.go
  pkg/urn/urn.go
  pkg/urn/urn_common.go
  pkg/urn/urn_common_test.go
  pkg/urn/urn_helpers.go
  pkg/urn/urn_is_funcs.go
  pkg/urn/urn_is_funcs_test.go
  pkg/urn/urn_is_methods.go
  pkg/urn/urn_is_methods_test.go
  pkg/urn/urn_test.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
  v1/edgegw.go
  v1/vdc.go
  v1/vdc_group.go
Labels: breaking-changes

#160 feat(egw): add ALB virtual service feature
  .changelog/160.txt
  v1/edgegw.go
  v1/edgegw_alb_virtual_service.go
  v1/edgegw_alb_virtual_service_types.go
  v1/edgegw_types.go
Labels: Feature

#177 chore: synced file(s) with orange-cloudavenue/workflows
  .pre-commit/go-mod
Labels: sync

#178 chore: synced file(s) with orange-cloudavenue/workflows
  .github/pull-request-size.yml
  .github/workflows/pr_open.yml
Labels: size/S, Chore, sync

#179 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr_open.yml
Labels: size/XS, Chore, sync
