Repository orange-cloudavenue/cloudavenue-sdk-go, pull requests merged in 2025-02, with the labels that each got.

#206 fix: org properties
  .changelog/206.txt
  v1/org/properties_types.go
Labels: size/XS, fix

#166 feat: add LoadBalancer
  .changelog/166.txt
  .golangci.yml
  pkg/urn/urn.go
  v1/edgegw_alb_virtual_service.go
  v1/edgegw_alb_virtual_service_types.go
  v1/edgeloadbalancer/client.go
  v1/edgeloadbalancer/pool.go
  v1/edgeloadbalancer/pool_constants.go
  v1/edgeloadbalancer/pool_test.go
  v1/edgeloadbalancer/pool_types.go
  v1/edgeloadbalancer/service_engine_group.go
  v1/edgeloadbalancer/service_engine_group_test.go
  v1/edgeloadbalancer/service_engine_group_types.go
  v1/edgeloadbalancer/zz_generated_client_test.go
  v1/org/mock/zz_generated_client.go
Labels: size/XL, feature

#210 fix: elb pool
  v1/edgeloadbalancer/pool_test.go
  v1/edgeloadbalancer/pool_types.go
Labels: size/S, fix

#212 feat: add ELB virtual service
  .changelog/211.txt
  pkg/helpers/validators/urn.go
  pkg/helpers/validators/validator.go
  pkg/urn/urn.go
  pkg/urn/urn_helpers.go
  v1/edgeloadbalancer/client.go
  v1/edgeloadbalancer/service_engine_group.go
  v1/edgeloadbalancer/service_engine_group_test.go
  v1/edgeloadbalancer/virtual_service.go
  v1/edgeloadbalancer/virtual_service_constants.go
  v1/edgeloadbalancer/virtual_service_test.go
  v1/edgeloadbalancer/virtual_service_types.go
  v1/edgeloadbalancer/zz_generated_client_test.go
Labels: size/XL, feature

#214 chore: synced file(s) with orange-cloudavenue/workflows
  .golangci.yml
  .pre-commit-config.yaml
Labels: size/S, sync, chore
